version: '3.1'

networks:
  testnetwork:

services:

  nodejs_ornek:
    image: tursoft/pardus-nodejs:8.15.1-ornek    
    networks:
      - testnetwork    
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    expose:
      - "8080"
    command: "npm start"      